### PR TITLE
Catkinized package

### PR DESCRIPTION
**Pull request by hdeeken**

### CODE REVIEW

**Comment by hdeeken** [comment]
added masterpackage
@jspricke: if you're fine with begin set as maintainer for this stack, i would say this can be merged
i'll comeback with another PR for the restructuring issues ;)

**Comment by hdeeken** [comment]
a f**k forgot to do this lint stuff... plz wait

**Comment by hdeeken** [comment]
mkay, now we're ready

**Comment by jspricke** [comment]
Fixed some minor things, squashed commits and merged.

**Pull request closed without merging**
